site_name: Splunk OpenTelemetry Java Workshop
site_url:
site_author: Tom Johander Observability Sales Engineer, Enterprise West
site_description: >-
  Learn to configure a Full-Stack Java Application to harness the entire Splunk Observavility Cloud Suite
repo_url: https://github.com/signalfx/otelworkshop/
edit_uri: ""
copyright: Copyright 2022 Splunk Inc. All rights reserved.
theme:
  name: material
  custom_dir: overrides
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  favicon: images/favicon.ico
  logo: images/logo.png
  font:
    text: "Century Gothic"
    code: Roboto Mono
  include_search_page: false
  search_index_only: true
  language: en
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.sections
    - navigation.expand
    - navigation.top
    # - toc.integrate

markdown_extensions:
  - footnotes
  - admonition
  - attr_list
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.mark
  - pymdownx.critic
  - pymdownx.keys
  - meta
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      permalink: true

extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/signalfx/otelworkshop
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/splunk
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/splunk/


nav:
  - Home: index.md
  - Introduction: introduction/introduction.md
  - Preparation: preparation/prep.md
  - Splunk Infrastructure Monitoring (IM): im/index.md
  - Splunk Application Performance Monitoring (APM): apm/index.md
  - Splunk Real User Monitoring (RUM): rum/index.md
  - Splunk Log Observer (LO): lo/index.md
